os: Windows Server 2012

environment:
  PRINTF_EXPONENT_DIGITS: "2"
  BUILD_TYPE: Release

install:
  - set HOME=.
  - set MSYSTEM=MINGW64
  - set PATH=C:/msys64/usr/bin;C:/msys64/mingw64/bin;%PATH%
  - set MINGWPREFIX=x86_64-w64-mingw32
  - set CC=%MINGWPREFIX%-gcc.exe
  - "sh -lc \"pacman -S --noconfirm --needed
      mingw-w64-x86_64-gcc
      mingw-w64-x86_64-cmake
    \""
  - ps: Get-Command sh.exe -All | Remove-Item


build_script:
  - mkdir build
  - cd build
  - cmake .. -G "MinGW Makefiles" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
  - cmake --build . --config %BUILD_TYPE% --target install
  - test\demo.exe
